### ISSUE TITLE
Request membership to the FEZ Github organisation by creating a new Issue in this repository. In the Issue, write up your name and what you work on (just a few words, we're curious!) and a brief description of what you want to contribute. We'll accept all relevant contributions, this step is just for us to know who is contributing and what they are contributing and grant membership.

### ISSUE THREAD

**Issue by annafdez** [FEZ-Finite-Element-Zurich/FEZ-Main-Info#13]

**Comment by evaherbst** [comment]
Hi Anna, could you give us a bit of information about your work and what you plan to contribute in the future?

**Comment by annafdez** [comment]
Hi! Sorry for the wrong message.

My name is Anna Fernandez

I am a medical resident in gynecology and obstetrics in Switzerland and
also MSB Biomedical engineer. I am currently collaborating with a
biomechanical research project in Lasuanne on the subject of dystocia.

Greetings,

*Anna Fernandez*
***@***.**** ***@***.***>
*0767993369*

**Comment by evaherbst** [comment]
Thank you Anna! Accepted membership
