### ISSUE TITLE
Request Membership

### ISSUE THREAD

**Issue by RostiReadioff** [FEZ-Finite-Element-Zurich/FEZ-Main-Info#15]
Hi team, 

I am Rosti Readioff, I am currently a research fellow at Leeds University on an EPSRC funded knee programme. I am working on developing specimen-specific pathological knee joint models in human. I use uCT and MRI scans to develop finite element models in Abaqus. In my previous work, I have also used point clouds to generate continuous solid FE for soft tissues such as knee ligaments. 
I would like to contribute to the workflows relating to using Abaqus and how to develop FEMs from point clouds.

Thanks,
Rosti

**Comment by evaherbst** [comment]
Thanks Rosti! The point cloud approach sounds super interesting!

Accepted :)
