### ISSUE TITLE
Request membership

### ISSUE THREAD

**Issue by mbarzegary** [FEZ-Finite-Element-Zurich/FEZ-Main-Info#2]
Name: Mojtaba Barzegari (https://mbarzegary.github.io/)

Current research topic: mathematical and computational modeling of biodegradation behavior of metallic implants and medical devices, in which I use finite element method to solve derived partial differential equations.

Contribution point: demonstration of the workflows that I employ for various modeling scenarios as well as providing fundamental training materials for understanding finite element method and variational formulation (like this one: https://github.com/mbarzegary/finite-element-intro).

**Comment by evaherbst** [comment]
Accepted, thanks for sharing this intro already! Feel free to fork it over at the end of the workshop already
